### ISSUE TITLE
Update existing envelopes with a webhook event notification URL

### ISSUE THREAD

**Issue by gh0st** [docusign/qs-csharp#3]
I'd like to update existing envelopes created from inside DocuSign with a webhook URL so that I can track those specific envelopes status'. If I know the envelope ID I figure I can "get" that envelope and then add the event notification to it like so

```c#
EventNotification eventNotification = new EventNotification();
eventNotification.Url = "https://my.docusign.webhook.url";
eventNotification.IncludeDocuments = "true";
List<EnvelopeEvent> envelopeEvents = new List<EnvelopeEvent>();
envelopeEvents.Add(new EnvelopeEvent { EnvelopeEventStatusCode = "completed", IncludeDocuments = "true" });
eventNotification.EnvelopeEvents = envelopeEvents;
```

I guess my question is, should I be doing this to an `Envelope` or should I be running this against the `EnvelopesApi`, by using on of the `EnveloesApi.Update*` methods?

**Comment by LarryKlugerDS** [comment]
Hi @gh0st ,
Unfortunately you cannot update an existing envelope to add the `eventNotification` attribute. The `eventNotification` attribute can only be used when the envelope is created via the API.

The `eventNotification` attribute can be used with any account pricing plan.

The account-level Connect webhook feature, if your account plan includes it, can be turned on at anytime. I do not know if it then covers envelopes that are in flight or not.

**Comment by gh0st** [comment]
@LarryKlugerDS, can I not add web hooks to envelopes created through the docusign portal? Ie, in docusign itself?

**Comment by LarryKlugerDS** [comment]
No, by design. If you want a webhook for an envelope created via the DocuSign web tool, then you need to use Connect account-level webhooks.

**Comment by gh0st** [comment]
Ah, understood. Thank you @LarryKlugerDS!
