### ISSUE TITLE
Endpoint Routing does not support 'IApplicationBuilder.UseMvc(...)

### ISSUE THREAD

**Issue by ivdinkov** [docusign/qs-csharp#4]
Application throwing exception after a fresh build with .NET Core 3.1.3

An error occurred while starting the application.
InvalidOperationException: Endpoint Routing does not support 'IApplicationBuilder.UseMvc(...)'. To use 'IApplicationBuilder.UseMvc' set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices(...).
Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action<IRouteBuilder> configureRoutes)

InvalidOperationException: Endpoint Routing does not support 'IApplicationBuilder.UseMvc(...)'. To use 'IApplicationBuilder.UseMvc' set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices(...).
Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action<IRouteBuilder> configureRoutes)
Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app)
qs_csharp.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in Startup.cs
+
            app.UseMvc();
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.ConfigureBuilder+<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter+<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, string startupMessage)
Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, string startupMessage)
Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
qs_csharp.Program.Main(string[] args) in Program.cs
+
            CreateWebHostBuilder(args).Build().Run();

Show raw exception details
.NET Core 3.1.3 X64 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 3.1.3    |    Microsoft Windows 10.0.18363    |   Need help?

**Comment by LarryKlugerDS** [comment]
I'm sorry you're having this problem. Please try our [new example for C#](https://github.com/docusign/code-examples-csharp). You'll need to first create an integration key for it using the esignature admin tool in the developer system, demo.docusign.net

**Comment by ivdinkov** [comment]
Looks like disabling EnableEndpointrouting fixed the issueservices.AddMvc(option => option.EnableEndpointRouting = false).SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

**Comment by LarryKlugerDS** [comment]
Thank you! I have filed bug report DEVDOCS-2775. And have included your fix in the report.

**Comment by ivdinkov** [comment]
Thank you

**Comment by ivdinkov** [comment]
Thank you. PR created

**Comment by InbarGazit** [comment]
PR merged. Closing Issue.
